version: '3.8'

services:
  db:
    image: postgres:15
    container_name: api_go
    restart: always
    environment:
      POSTGRES_USER: admin      
      POSTGRES_PASSWORD: admin  
      POSTGRES_DB: apigo
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes: 
  pgdata:
